os: ubuntu

branches:
  only:
    - master
  
language: c
sudo: required
before_install:
  - pwd
  - ls
  - sudo apt-get install gfortran cmake libgtest-dev libblas-dev liblapack-dev
  - cd /usr/src/gtest
  - sudo cmake CMakeLists.txt
  - sudo make
  - sudo mkdir lib/
  - sudo cp *.a lib/
  - export GTEST=/usr/src/gtest/

script:
  - cd /home/travis/build/jmorris-uk/fortran-googletest
  - cmake -H. -Bbuild
  - cmake --build build
  - ./bin/GTest.exe
