# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    pwd
    ls
    sudo apt-get install gfortran cmake libgtest-dev libblas-dev liblapack-dev
    cd /usr/src/gtest
    sudo cmake CMakeLists.txt
    sudo make
    sudo mkdir lib/
    sudo cp *.a lib/
    export GTEST=/usr/src/gtest/
    cd ~/work/1/
    ls
    pwd
    cmake -H. -Bbuild
    cmake --build build
    ./bin/GTest.exe
  displayName: 'Run a googletest'
