name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      run: |
        pwd
        sudo apt-get update -y
        sudo apt-get install -y libgtest-dev gfortran g++ cmake
        cd /usr/src/gtest
        sudo cmake CMakeLists.txt
        sudo make
        mkdir lib
        sudo cp *.a lib
        export GTEST=/usr/src/gtest/
        cd /home/runner/work/fortran-googletest/fortran-googletest
        ls
        pwd
        sudo cmake -H. -Bbuild
        sudo cmake --build build
        cd build
        ./bin/GTest.exe
