name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      run: |
        apt-get install -y libgtest-dev
        apt-get install -y cmake
        cd /usr/src/gtest
        cmake CMakeLists.txt
        make
        mkdir lib/
        cp *.a lib/
        export GTEST=/usr/src/gtest/
        cmake -H. -Bbuild
        cmake --build build
        ./bin/GTest.exe
