name: CI Build and Test

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run a multi-line script
      run: |
        pwd
        sudo apt-get update -y
        sudo apt-get install -y libgtest-dev gfortran g++ cmake libblas-dev liblapack-dev
        cd /usr/src/gtest
        sudo cmake CMakeLists.txt
        sudo make
        cd /home/runner/work/fortran-googletest/fortran-googletest
        ls
        pwd
        sudo cmake -H. -Bbuild
        sudo cmake --build build
        ./bin/GTest.exe
